---
title: "Read counts overview"
output: 
  html_document:
    css: style.css
---

# Introduction
This script produces a simple histogram of the number of UMIs per cell in an example data-set.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.width=10, fig.height=6)
library(Seurat)
library(tidyverse)
library(TENxPBMCData)

folder <- 'read_count_overview/'
dir.create(folder)
```
# pbmc3k
To show the high variance in the number of observed UMIs per cell in a typical 10X experiment we will use the popular 10X pbmc3k data-set.

The histogram below shows the UMIs/cell, they span roughly one order of magnitude.

```{r make_plot}
pbmc3k <- TENxPBMCData(dataset = "pbmc3k")

read_count_data <- tibble(`UMIs/cell` = colSums(assay(pbmc3k)))
read_count_plot <- ggplot(read_count_data) + geom_histogram(aes(x = `UMIs/cell`), bins = 30, fill = "#3182BD", color = 'white') + scale_x_continuous(limits = c(0,7000)) + theme_classic()

read_count_plot

ggsave(str_glue('{folder}read_count_plot.pdf'), read_count_plot, width = 6.6, height = 4)
saveRDS(file = str_glue('{folder}read_count_plot.Rds'), read_count_plot)

```

